version: '3'
services:
  my-postgres:
    image: postgres
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_PASSWORD=Revature@22
    volumes:
      - ./dbscript.sql:/docker-entrypoint-initdb.d/create_tables.sql
  javalin-backend-service:
    image: javalin-backend
    build: .
    ports:
      - 9999:2020
    depends_on:
      - my-postgres
    links:
      - my-postgres