pipeline {
	agent any
	stages {
		stage ('Clone Code') {
			steps {
				git branch: 'master', url: 'git@github.com/kleanarev/Reim'
			}
		}
		
		stage ('Build Code') {
			steps {
				sh 'mvn clean package'
			}
		}
		
		stage ('Staging') {
			steps {
				sh 'docker-compose down'
				sh 'docker-compose up -d'
			}
		}
	}
}
